### ISSUE TITLE
Support DynamoDB Tables with a Sort key

### ISSUE THREAD

**Issue by ryanwilliams83** [awslabs/aws-dotnet-distributed-cache-provider#51]
### Describe the feature

Implement support for tables with a composite primary key of string/string.

### Use Case

I'm using the Single Table pattern for my application with a Partition Key: `PK (String)` and a Sort Key: `SK (String)`

I'm believe that I am unable to use this component with this component due to the error `AWS.DistributedCacheProvider.DynamoDBDistributedCacheException: Failed to get Item with key 049096df-ae0e-ed8e-c649-0a9b58ad027d. Caused by The provided key element does not match the schema`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS.AspNetCore.DistributedCacheProvider package version

AWS.AspNetCore.DistributedCacheProvider (0.9.3)

### Targeted .NET Platform

.NET 6

### Operating System and version

public.ecr.aws/lambda/dotnet:6

**Comment by normj** [comment]
@ryanwilliams83 Can you provide some more information on how you are setting the key and in this case what you would expect the sort key to be set to? We added in this library the `PartitionKeyPrefix` option to support allowing the data for the distribute cache to coexist with data for another purpose. Since this library doesn't have a use case for needing a sort key we could allow configuring it to always set a fixed value for a sort key if one exists.

**Comment by ashishdhingra** [comment]
While trying to reproduce the issue with a DynamoDB table having partition and sort keys, I got an error `Table test-distributed-cache cannot be used as a cache because it contains a range key in its schema. Cache requires a non-composite Hash key of type String.` due to validation [here](https://github.com/awslabs/aws-dotnet-distributed-cache-provider/blob/82bc3335ea2f192ad4bf117029d4de90ae83aea6/src/AWS.DistributedCacheProvider/Internal/DynamoDBTableCreator.cs#L77). I guess this is per design since DynamoDB table is being used as distributed cache with key/value pair. I'm unsure how `SortKey` could be used as part of key for storage and retrieval.
